RECIPE-API_DATABASE_USER: 'database  user'
RECIPE-API_DATABASE_PASSWORD: 'database password'
RECIPE-API_DATABASE_HOST: 'localhost'
RECIPE-API_DATABASE: 'database name'
RECIPE-API-TEST_DATABASE: 'test database'
SENDGRID_API_KEY: 'sendgrid API key'
SENDGRID_PASS: 'sendgrid password'
SENDGRID_USER: 'sendgrid username'
PRODUCTION_HOST: 'rezept-api.herokuapp.com'
